# Generated by Django 4.1 on 2024-01-31 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('core', '0004_pontoturistico_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='Avaliacao',
            field=models.ManyToManyField(to='avaliacoes.avaliacao'),
        ),
    ]
